In [1]:
import numpy as np
print(dir(np))

['ALLOW_THREADS', 'BUFSIZE', 'CLIP', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_builtins', '_distributor_init', '_financial_names', '_get_promotion_state', '_globals', '_int_extended_ms

In [9]:
x = np.array([2,5,6,7,8,1])     # it is a array
print(x)
print(type(x))
y = [5,7,8,5,4,3,0]    # it is a list in python
print(y,type(y))

[2 5 6 7 8 1]
<class 'numpy.ndarray'>
[5, 7, 8, 5, 4, 3, 0] <class 'list'>


In [11]:
%timeit [j**4 for j in range(1,9)]      # more time consume in list 

1.41 µs ± 26 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [12]:
%timeit np.arange(1,9)**4

3.95 µs ± 43.3 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [17]:
list = []
for i in range(1,6):
    list_1 = int(input("Enter the number:"))
    list.append(list_1)
print(np.array(list))

Enter the number: 45
Enter the number: 67
Enter the number: 33
Enter the number: 89
Enter the number: 21


[45 67 33 89 21]


In [18]:
one_dimension = np.array([2,4,5,6,7,9])
print(one_dimension)
print(one_dimension.ndim     # to find the dimension of array

[2 4 5 6 7 9]
1


In [19]:
two_dimension = np.array([[2,4,5,6,7,9],[6,8,3,4,0,1]])
print(two_dimension)
print(two_dimension.ndim)   # to find the dimension of array

[[2 4 5 6 7 9]
 [6 8 3 4 0 1]]
2


In [21]:
three_dimension = np.array([[[2,4,5,6,7,9],[6,7,8,3,2,1],[7,0,9,7,6,3]]])
print(three_dimension)
print(three_dimension.ndim)     # to find the dimension of array

[[[2 4 5 6 7 9]
  [6 7 8 3 2 1]
  [7 0 9 7 6 3]]]
3


In [22]:
multi_dimension = np.array([2,4,5,6,7,9],ndmin = 10)
print(multi_dimension)
print(multi_dimension.ndim)     # to find the dimension of array

[[[[[[[[[[2 4 5 6 7 9]]]]]]]]]]
10


In [24]:
arr_zero = np.zeros(4)
arr_zero1 = np.zeros((4,5))
print(arr_zero)                     # array of only zero element
print()
print(arr_zero1)

[0. 0. 0. 0.]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [25]:
arr_one = np.ones(4)                       
arr_one1 = np.ones((3,5))
print(arr_one)                     # array of only one element
print()
print(arr_one1)

[1. 1. 1. 1.]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [26]:
arr_em = np.empty(8)
print(arr_em)                          # it is a empty array


[0. 0. 0. 0. 0. 0. 0. 0.]


In [27]:
# Range array

In [28]:
arr_range = np.arange(5)
print(arr_range)

[0 1 2 3 4]


In [29]:
# Digonal element  is one 

In [31]:
arr_digonal = np.eye(3)             # 3*3 ka ek matrix create hoga jiske digonal element 1 hoga 
print(arr_digonal)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [32]:
arr_digonal = np.eye(3,5)             # 3*3 ka ek matrix create hoga jiske digonal element 1 hoga 
print(arr_digonal)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [33]:
#linespace

In [39]:
arr_Line = np.linspace(0,10,num=4)
print(arr_Line)

[ 0.          3.33333333  6.66666667 10.        ]


In [1]:

# Random array create
#Rand()

In [7]:
import numpy as np
var = np.random.rand(4)
var1 = np.random.rand(3,4)      # 3 number of row and 4 is number os column
print(var)
print()
print(var1)

[0.76017349 0.03393109 0.55458356 0.64096866]

[[0.40626076 0.66996735 0.36395926 0.55412671]
 [0.26338101 0.2399713  0.45029428 0.02161999]
 [0.31823764 0.95956292 0.1429348  0.25830325]]


In [8]:
# Ranf()

In [10]:
var2 = np.random.ranf(4)
print(var2)

[0.41804346 0.80523668 0.06228558 0.67029966]


In [11]:
#Randint()

In [12]:
var3 = np.random.randint(4,30,6)     # randint(min,max,total_element in array)
print(var3)

[10 14 18 23 15 20]


In [13]:
#Randn

In [14]:
var4 = np.random.randn(5)      # randn me 0 to 1 ke bich nearest to zero positive or negative
print(var4)

[-0.79077789 -0.69147557  1.34712473 -0.05017391  0.66412568]


In [1]:
numbers <- 1:10

# Calculate the sum of numbers
sum_of_numbers <- sum(numbers)

# Print the result
print(paste("The sum of numbers from 1 to 10 is:", sum_of_numbers))

SyntaxError: illegal target for annotation (3981010744.py, line 1)