In [1]:
# Shape

In [2]:
import numpy as np
var = np.array([[3,4,5,8],[4,6,8,0]])
print(var)
print(var.shape)
print(var.ndim)


[[3 4 5 8]
 [4 6 8 0]]
(2, 4)
2


In [3]:
var1 = np.array([3,6,7,8,3],ndmin = 4)
print(var1)
print(var1.shape)         #  
print(var1.ndim)

[[[[3 6 7 8 3]]]]
(1, 1, 1, 5)
4


In [4]:
# Reshape

In [19]:
var2 = np.array([3,4,5,6,7])
print(var2)
print(var2.ndim)
print()
x = var2.reshape(5,1,1)        # reshape me (row,colum) jo hame chahiye  and row * colum = number of element in array
print(x)
print(x.ndim)
print(x.shape)
print()
one = x.reshape(-1)   # for multidimension ko one dimession me convert karna
print("One dimession array",one)

[3 4 5 6 7]
1

[[[3]]

 [[4]]

 [[5]]

 [[6]]

 [[7]]]
3
(5, 1, 1)

One dimession array [3 4 5 6 7]


In [20]:
# Brodcast

In [23]:
a = np.array([[3,5,7],[7,9,1]])                  # 2*3  = 2*1
print(a.shape)                                   # right se left pr dono me kisi me 1 ho to 3*1 addition perfrom hoga
b = np.array([[2],[6]])                           # 2 *2 same 
print(b.shape)                                   # result = maximum in both 2*3
print(a+b)

(2, 3)
(2, 1)
[[ 5  7  9]
 [13 15  7]]


In [25]:
a = np.array([[3,5,7],[7,9,1]])                  # 2*3  = 2*1
print(a.shape)                                   # right se left pr dono me kisi me 1 ho to 3*1 addition perfrom hoga
b = np.array([[2],[6],[5]])                           # 2 *2 same 
print(b.shape)                                   # result = maximum in both 2*3
print(a+b)

(2, 3)
(3, 1)


ValueError: operands could not be broadcast together with shapes (2,3) (3,1) 

In [26]:
# Indexing

In [27]:
var = np.array([[3,4,5],[8,9,1]])
print(var)
print(var[1,1])

[[3 4 5]
 [8 9 1]]
9


In [28]:
var = np.array([[[3,4,6,7],[8,9,0,2]]])
print(var)
print(var[0,1,2])

[[[3 4 6 7]
  [8 9 0 2]]]
0


In [29]:
#Slicing

In [32]:
x = np.array([4,6,7,8,9,2,3,4,67,54,21,6,55])
#index        0,1,2,3,4,5,6,7,8,9,10,11,......
#negative index       ...........,-4-3,-2-1

print("7 to 3 :",x[2:7])      # [start:stop:step]

print()

print("stop : ",x[::2])   
print(x[2:10:3])        # tow step jump  from 2 index to 9 index
# similar to string slicing

7 to 3 : [7 8 9 2 3]

stop :  [ 4  7  9  3 67 21 55]
[ 7  2 67]


In [33]:
# slicing for two dimenssion array

In [36]:
y = np.array([[3,4,5,6,7,8],[8,9,0,2,1,3],[5,6,9,7,2,4]])
print(y.ndim)
print(y)
print(y.shape)

print()
print("to find 9 to 1 element : ",y[1,1:5])

2
[[3 4 5 6 7 8]
 [8 9 0 2 1 3]
 [5 6 9 7 2 4]]
(3, 6)

to find 9 to 1 element :  [9 0 2 1]
