In [1]:
# copy    in copy if we change in first variable then no change in copy variable 

In [12]:
import numpy as np
var = np.array([4,5,7,8,9])
c = var.copy()        # create copy of var in c variable 

var[2] = 55

print(var)
print()
print(c)

[ 4  5 55  8  9]

[4 5 7 8 9]


In [3]:
# view    in view if we change in first variable then same data is change in copy variable 

In [11]:
x = np.array([4,6,2,5,2])
y = x.view()
x[2] = 55
print(x)
print()
print(y)


[ 4  6 55  5  2]

[ 4  6 55  5  2]


In [2]:
import numpy as np
arr = np.array([45,89,43,23,80])
x = arr[[True,False,True,True,False]]
print(x)

[45 43 23]
